{
  "name": "Hinet-TW",
  "email": "xxxx@gmail.com",
  "api_key": "xxxxxxxx",
  "domain": "example.xyz",
  "changeHinetIpUrl": "xxxxxxxxxxx",
  "TGBotAPI": "xxxxxxxxxxxxxxx",
  "chartId": "xxxxxxxxxxxx",
  "ddnsUrl": "xxxxxxxxxxxxxx",
  "checknfport": "10241",
  "checkgfwport": "10242",
  "checkGFWUrl": "xxxxxxxxxxxxxxxxxxxxx",
  "changeIPCrons": "0 3 * * *",
  "checkNfGfwCron": "*/10 * * * *"
   "authorized_users": ["AS99294837"]

}